/* Dependency-free tests for the ESM + library surface. Run: node esm.test.mjs
 *
 * These exist because the measured audience for this tool (developers whose
 * schema is generated by Zod/Pydantic inside Vercel AI SDK, LangChain, LiteLLM,
 * Mastra) is on ESM + TypeScript. Before this file, `import { convert } from
 * "llm-json-schema"` threw SyntaxError and there were no type definitions —
 * the library form was unusable for exactly the people it targets.
 *
 * A regression here means the tool is once again importable only by the
 * audience that does NOT have this problem.
 */
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import api, {
  convert,
  inferSchema,
  looksLikeSchema,
  toOpenAI,
  toAnthropic,
  toGemini,
  DOCS
} from "./engine.mjs";

const here = dirname(fileURLToPath(import.meta.url));
let pass = 0, fail = 0;

function ok(name, cond, detail) {
  if (cond) { pass++; console.log("  ok  " + name); }
  else { fail++; console.log("FAIL  " + name + (detail ? "\n        " + detail : "")); }
}

// --- named exports resolve ---------------------------------------------------
for (const [name, fn] of Object.entries({
  convert, inferSchema, looksLikeSchema, toOpenAI, toAnthropic, toGemini
})) {
  ok("named export `" + name + "` is a function", typeof fn === "function", typeof fn);
}
ok("named export `DOCS` carries all three providers",
  ["openai", "anthropic", "gemini"].every((p) => typeof DOCS[p] === "string"),
  JSON.stringify(DOCS));

// --- default export still works (back-compat with the CJS consumers) ---------
ok("default export exposes the same convert", api.convert === convert);

// --- object input: the whole point for Zod/Pydantic callers -------------------
// This is the zod-to-json-schema output shape for
//   z.object({ args: z.object({}) })
// which OpenAI rejects with "Missing 'args'" unless every key is in `required`.
const ZOD_OUTPUT = {
  type: "object",
  properties: { args: { type: "object", properties: {} } }
};

(function () {
  const r = convert(ZOD_OUTPUT, "openai");
  ok("convert() accepts a parsed object (no JSON.stringify needed)", r.ok, r.error);
  ok("object input produces a strict-valid schema",
    r.ok && r.schema.required.indexOf("args") !== -1 && r.schema.additionalProperties === false,
    JSON.stringify(r.ok && r.schema));
  ok("object input is not treated as a sample value to infer from",
    r.ok && r.inferred === false);
})();

(function () {
  // The caller's schema object must survive untouched — they are usually about
  // to reuse it for another provider or hand it back to their own SDK.
  const before = JSON.stringify(ZOD_OUTPUT);
  convert(ZOD_OUTPUT, "openai");
  convert(ZOD_OUTPUT, "gemini");
  ok("convert() does not mutate the caller's object", JSON.stringify(ZOD_OUTPUT) === before,
    JSON.stringify(ZOD_OUTPUT));
})();

(function () {
  // String input must keep behaving exactly as before.
  const fromString = convert(JSON.stringify(ZOD_OUTPUT), "openai");
  const fromObject = convert(ZOD_OUTPUT, "openai");
  ok("string and object input give identical results",
    JSON.stringify(fromString.schema) === JSON.stringify(fromObject.schema));
})();

(function () {
  const r = convert(42, "openai");
  ok("non-object, non-string input fails cleanly", r.ok === false && /Expected a JSON string/.test(r.error), JSON.stringify(r));
  const n = convert(null, "openai");
  ok("null input fails cleanly", n.ok === false && /null/.test(n.error), JSON.stringify(n));
})();

// --- provider divergence is still the value prop ------------------------------
(function () {
  const oa = convert(ZOD_OUTPUT, "openai");
  const an = convert(ZOD_OUTPUT, "anthropic");
  ok("the same schema diverges between OpenAI and Anthropic",
    JSON.stringify(oa.schema) !== JSON.stringify(an.schema));
})();

// --- the published surface actually ships ------------------------------------
(function () {
  const pkg = JSON.parse(readFileSync(join(here, "package.json"), "utf8"));
  ok("package.json declares types", pkg.types === "index.d.ts");
  ok("index.d.ts exists", existsSync(join(here, "index.d.ts")));
  ok("exports map routes import -> engine.mjs", pkg.exports["."].import === "./engine.mjs");
  ok("exports map routes require -> engine.js", pkg.exports["."].require === "./engine.js");
  for (const f of ["engine.js", "engine.mjs", "index.d.ts", "cli.js"]) {
    ok("`files` ships " + f, pkg.files.indexOf(f) !== -1, JSON.stringify(pkg.files));
  }

  // Every runtime named export must be declared in the .d.ts, or TS users get
  // a compile error on a function that exists.
  const dts = readFileSync(join(here, "index.d.ts"), "utf8");
  for (const name of Object.keys(api)) {
    ok(".d.ts declares `" + name + "`", new RegExp("export (declare )?(function|const) " + name + "\\b").test(dts));
  }
})();

ok("`gemini-client` is a documented provider over ESM",
  typeof DOCS["gemini-client"] === "string" && DOCS["gemini-client"].length > 0);

console.log("\n" + pass + " passed, " + fail + " failed");
process.exit(fail ? 1 : 0);
